### ISSUE TITLE
David Honítko

### ISSUE THREAD

**Issue by sssvt-kopecky-michal** [sssvt-chrpa-jakub/Students#2]
David Honítko
![123457263_818587548901425_1ss364679601379924780_n](https://user-images.githubusercontent.com/74187844/100215928-f23d8680-2f11-11eb-975c-e00b55bd1e5c.png)

**Comment by sssvt-kopecky-michal** [comment]
David Honitko

**Comment by sssvt-chrpa-jakub** [comment]
Ahoj, díky za upozornění, mrknu na to. ;)
